routes:
  - name: articles.index
    method: GET
    path: /articles
    handler: App\Controller\ArticleController::index
  
  - name: articles.show
    method: GET
    path: /articles/[i:id]
    handler: App\Controller\ArticleController::show
  
  - name: home.index
    method: GET
    path: /
    handler: App\Controller\HomeController::home