routes:
  - name: home
    method: GET
    path: /articles/[i:id]
    handler: App\Controller\ArticleController::index
  
  - name: home.index
    method: GET
    path: /
    handler: App\Controller\ArticleController::index